### PR TITLE
Migrate ci to GitHub actions #17

### LINKED ISSUE #17: Migrate CI from Travis to Github Actions
**Description**:
It would be useful to migrate CI builds from Travis to GitHub Actions.

**Acceptance criteria**:
- [ ] CI builds run

### PR DESCRIPTION
**Pull request by VKTB**
## Description
Migrates the Travis CI build to GitHub actions.

## Testing instructions
- [x] Review code
- [x] Check CI build runs in GitHub actions
- [ ] Check GitHub actions successfully publishes site (Can only be tested once the PR is merged)

## Agile board tracking
closes #17

### CODE REVIEW

**Comment by VKTB** [comment]
The workflow successfully build the site before the last commit was pushed, so we now need to test whether it publishes the site OK when the PR is merged.

**Review by louise-davies — CHANGES_REQUESTED** [review]
This would now mean that non-`gatsbyjs` branches are never tested on CI - I think we should add back in that behaviour.

**Comment by VKTB** [comment]
> This would now mean that non-`gatsbyjs` branches are never tested on CI - I think we should add back in that behaviour.

@louise-davies Running the current workflow on non-gatsbyjs branches would mean that it would be deployed on every push. While there is a `skip-publish: true` that allows for the deploy part to be skipped, I could not find a way to make use of it for non-gatsbyjs branches only at the time of writing the workflow. I will have a look again next week.

**Comment by VKTB** [comment]
@louise-davies I modified the workflow so that it builds but skips publishing for non `gatsbyjs` branches.
image

**Review by louise-davies — APPROVED** [review]
Looks good and I can see it now ran in this PR - let's now see if the publishing works!

**Comment by agbeltran** [comment]
great work @VKTB and @louise-davies !

**Pull request merged**
