### PR TITLE
WIP: It closes #30

### LINKED ISSUE #30: Include details for ESRF
The [facilities page](https://icatproject.org/collaboration/facilities/) does not mention ESRF. @andygotz @antolinos could you please provide some text?

### PR DESCRIPTION
**Pull request by antolinos**

### CODE REVIEW

**Review by andygotz — COMMENTED** [review]
Can you add a short description on the new features ESRF has developed i.e. logbook, ICAT+, etc.?

Can you give the precise number of beamlines storing data in ICAT today i.e. 32 and in the future 40. We should mention that we are ingesting data in real time too.

**Comment by agbeltran** [comment]
@antolinos are you able to add the additional features to the PR? Do let us know when it is ready for review and merge.

**Comment by antolinos** [comment]
Please @andygotz  if you have the chance have a look at the page to see if you are missing anything
https://github.com/icatproject/icatproject.github.io/blob/b3b7d29dc927dadc4cb6ab81292d79b63e9f9523/content/collaboration/facilities/esrf.md

**Comment by agbeltran** [comment]
@andygotz are you happy with the current text?

(we need to fix a token issue on the publication workflow on our side, but we can do that later)

**Comment by andygotz** [comment]
@agbeltran the text is fine for me. It reflects the situation at the ESRF well. Please go ahead and publish it.

**Pull request merged**
