### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by louise-davies**
Some UI improvements that we discussed - e.g. adding permanent layout component, fixing some CSS issues, improving SEO etc.

### CODE REVIEW

**Review by stuartpullinger — CHANGES_REQUESTED** [review]
All looks good - on Firefox... Please could you look into a layout bug in Chrome: The green search button hangs down a bit from the rest of the navigation bar.

The typeface for the headings in the sidebar looks bolder and more tightly kerned in Chrome than in Firefox. Could the navigation bar be inheriting the height of the 'ICAT Project' text - which happens to match the height of the search button on Firefox but not on Chrome? Could you:
a) make the heading typefaces the same on Firefox and Chrome?
b) make the search button inherit its height from the navigation bar?

Also, while you are looking into this, could you add some more space above the 'ICAT Project' text in the top left? It looks a bit squished to me.

**Comment by louise-davies** [comment]
@stuartpullinger thanks for checking this out on chrome - totally forgot to do that myself! I'll look into these issues this afternoon

**Comment by louise-davies** [comment]
The issues in order:
- I wasn't overriding the default button padding in chrome, hence the button being a little larger
- I wasn't fetching the bold fonts, hence causing odd aliasing issues
- added some extra margin to the top + bottom of the website header

Let me know if these fixes/changes are what you imagined :)

**Review by VKTB — APPROVED** [review]
Looks good

**Pull request merged**
